### ISSUE TITLE
Parser configuration problem: namespace reporting is not enabled

### ISSUE THREAD

**Issue by paulsen-it** [sapstern/-edifactconverter-#28]
I get the error "Parser configuration problem: namespace reporting is not enabled" on parseEdifact.

I use the sample code from this project:
```
        InputStream inputStream = Sample01.class.getResourceAsStream("/orders.edi");
        BufferedReader in = new BufferedReader(new InputStreamReader(inputStream, "UTF8"));
        String contents = in.readLine();
    	EdifactSaxParserToXMLIF theXmlParser = EdifactSaxParserToXML.factory("UTF-8");
    	String edifactXml = theXmlParser.parseEdifact(contents);
        System.out.println(edifactXml);
```

on the line `String edifactXml = theXmlParser.parseEdifact(contents);` I got the error.

Here is the Stacktrace:
```
Okt 06, 2021 1:13:22 PM com.sapstern.openedifact.sax.EdifactSaxParserToXML parse
INFORMATION: xsdFileName EDIFACTINTERCHANGE_ORDERS_97A
Error 
  Error reported by XML parser processing null: Parser configuration problem: namespace
  reporting is not enabled
Error reported by XML parser processing null: Parser configuration problem: namespace reporting is not enabled
net.sf.saxon.trans.XPathException: Error reported by XML parser processing null: Parser configuration problem: namespace reporting is not enabled
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:410)
	at net.sf.saxon.event.Sender.send(Sender.java:143)
	at net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:46)
	at com.sapstern.openedifact.sax.EdifactSaxParserToXML.parseEdifact(EdifactSaxParserToXML.java:1169)
	at com.sapstern.openedifact.sax.EdifactSaxParserToXML.parseEdifact(EdifactSaxParserToXML.java:1145)
	at de.edi.ProcessorInit.process(ProcessorInit.java:52)
...
```

What I do wrong? Thank you for any help.

EDIT: I found a strange point. My project is a Maven project and I have the dependency to saxon. If I see right you use sax. But when I use your project as a library, your Project use also saxon.

**Comment by sapstern** [comment]
Hello, 

I guess it has something to do with the sax parser you are using.

I can try it myself, if you are handing over your edifact source.

Best 

Matthias

**Comment by paulsen-it** [comment]
Hello sapstern,

here is my EDI Order. I found out, that on EdifactSaxParserToXML.java Method parseCurrentSegment in the last else tree the namespace is empty while isNamepace = true. Why I don't know.

[ORDERNoName.txt](https://github.com/sapstern/edifactconverter/files/7520327/ORDERNoName.txt)

Thank you for any help.
