### ISSUE TITLE
Mojibake issue with character set 'UNOY'

### ISSUE THREAD

**Issue by Orca007** [sapstern/-edifactconverter-#30]
Same issue as last time, while the character set 'UNOY'
input EDI is:

> UNA:+.? 'UNB+UNOY:4::7+878542765:1:315000554+91310114786742945M:SAIC+20210927:0933+71073573917223++IFCSUM'UNH+71073573917223+IFCSUM:D:08A:UN'BGM+610+4116356222+9'FTX+AAI+++Goods of chem. Industry'FTX+AAI+++Please mention for further inquiries and accounting?: 4116356222'FTX+AAK+++Please book in accordance to existing freight agreements'FTX+PKG+++AP?: Truck generic'CNT+7:1344.00:KGM'CNT+11:8:C62'CNT+16:2:D97'CNT+19:42.00:KGM'CNT+15:2.792:MTQ'RFF+AHI:4116356222'DTM+171:202109270932:203'RFF+ACE:YE33'RFF+ALZ:264'TDT+20++3+31'DTM+81:20210928:102'FTX+EUR+++Local truck shipment'FTX+TRA+++Street:10'FTX+TRA+++AP?: Truck generic'NAD+CS+2329657:160:86++上海晓荣物流有限公司+嘉定区澄浏中路1228号6幢2层+上海+SHI::86:上海市+201801+CN'CTA+TR'COM+02159907073:TE'COM+02159907073:FX'COM+linna@vip.126.com:EM'NAD+CZ+195362:160:86++巴斯夫( 中国 )有限公司+浦东江心沙路300号+上海市+SHI::86:上海市+200137+CN'CTA+SD+CN61'CTA+TR+A-EDA/GSO:Mrs ZHENG Ying Jasrine'COM+?+86212039:TE'COM+JASRINE.ZHENG@BASF.COM:EM'NAD+FP+195362:160:86++巴斯夫( 中国 )有限公司+浦东江心沙路300号+上海市+SHI::86:上海市+200137+CN'EQD+CN+1064824613'CNI+1+6210802264'DTM+63:20211002:102'DTM+63:08301730:501'CNT+11:8:PCE'CNT+29:1200.00:KGM'CNT+7:1344.00:KGM'CNT+16:2:D97'CNT+99:42.00:KGM'TOD+5++DDP'LOC+1+:::TIANJIN'NAD+CN+2821548:160:86+东丽区+北京美扬时代科贸有限公司+荣明达物流金钟路金钟工业园区金发道3号路+天津+TJN::86:天津市+300163+CN'CTA+CN+:天津荣明达物流'COM+15332112687:TE'GID+1+2:CP3:67:91:Pallet,wood,CP3,1140x1140x138mm,HT+8:1A1:67:91:钢桶'PIA+5+55713536:SA'PIA+5+3208909010:HS'PIA+1+YAP00019 GC DG'FTX+AAA+++埃夫卡® SI 2040 消泡剂 150KG Metal-Drum, non rem.hd. 1A1'FTX+PAC+++Pallet, wood, CP3, 1140x1140x138mm, HT'FTX+AHF+++ED2'NAD+PW+7C61/WH15:160:86'NAD+WQ+++RA'MEA+WT+AAL+KGM:1200.000'MEA+WT+AAE+KGM:1344.000'MEA+WT+WT+KGM:42.000'MEA+TE+TC:::Flash Point+CEL:49.00'DIM+3+MMT:1170.0:1170.0:1020.0'RFF+LI:6210802264:000010'RFF+VN:6009402806:000020'RFF+OP:20210402006'RFF+UC:20210402006'DTM+4:20210402:102'RFF+SF:7C61:WH15'DTM+181:202109280000:203'DTM+200:073000163000:502'DGS+ADR+3+1993+49.0:CEL+3+++++3'FTX+AAD+++中国道路运输危险货物信息 UN 1993, 正式运输名称： 易燃液体，未另作规定的 ( 2,6-二甲基庚烷-4-酮, 溶剂 石脑油), 类别或项别 3, 包装类别 III'DGS+TEC'FTX+ACB+++Odor?: 特有的'FTX+AAN+++Suitable Materials For Packages?: 耐热漆 RDL 50, 耐热漆 R 78433, 烤干漆（Stove-lacquer AV500）, 玻璃, 高密度聚乙烯, 碳钢（铁）, 氟化高密度聚乙烯'UNT+73+71073573917223'UNZ+1+71073573917223'

Please help to check, thanks!

**Comment by sapstern** [comment]
I changed charset behaviour for UNOY, plz check
