### ISSUE TITLE
UNG is not supported

### ISSUE THREAD

**Issue by Jimex** [sapstern/-edifactconverter-#33]
I tried to convert a DESADV with a UNG segment, but it seems like the converter just ignore all the segments within the functional group.

**Comment by sapstern** [comment]
Hello, 
plz send me some of your sample EDI files, so that I can test the issue. 

I have now incorporated UNG / UNE segment.

This needs to get tested.

**Comment by Jimex** [comment]
Hello,

Here is one of the samples:

UNA:+.? '
UNB+UNOC:3+123456789PROD:16+FDX123456+220526:1124+IG-08727547++++1'
UNG+ORDERS+123456789PROD+FDX123456+220526:1124+FG-08727548+UN+D:97A'
UNH+359972299+ORDERS:D:97A:UN'
BGM+220'
DTM+137:20180526112421:204'
FTX+COI+++NP'
FTX+ACO+++ZZ03'
FTX+ACP+++Z43'
RFF+CO:9704875521'
DTM+4:20220526:102'
NAD+SU+0001900344'
TOD+++DCA:::Dedicated Carrier'
LIN+00010'
IMD+C++:::IT09738'
IMD+E++:::ZZZZ DLK LBL D5-9999U NVP Y-TPM: WIN'
QTY+21:47:EA'
DTM+2:20220527:102'
FTX+LIN+++ID?:2093834397'
RFF+AIS:A201'
LOC+ZZZ+1001'
UNS+S'
UNT+20+359972299'
UNE+1+FG-08727548'
UNZ+1+IG-08727547'

**Comment by sapstern** [comment]
Hello,

thats the result:
<?xml version="1.0" encoding="UTF-8"?><EDIFACTINTERCHANGE xmlns="urn:sapstern.com:EDIFACTINTERCHANGE_ORDERS_97A">
    <S_UNA>
        <D_UNA1>:</D_UNA1>
        <D_UNA2>+</D_UNA2>
        <D_UNA3>.</D_UNA3>
        <D_UNA4>?</D_UNA4>
        <D_UNA5>*</D_UNA5>
        <D_UNA6>'</D_UNA6>
    </S_UNA>
    <S_UNB>
        <C_S001>
            <D_0001>UNOC</D_0001>
            <D_0002>3</D_0002>
        </C_S001>
        <C_S002>
            <D_0004>123456789PROD</D_0004>
            <D_0007>16</D_0007>
        </C_S002>
        <C_S003>
            <D_0010>FDX123456</D_0010>
        </C_S003>
        <C_S004>
            <D_0017>220526</D_0017>
            <D_0019>1124</D_0019>
        </C_S004>
        <D_0020>IG-08727547</D_0020>
        <D_0031>1</D_0031>
    </S_UNB>
    <S_UNG>
        <D_0038>ORDERS</D_0038>
        <C_S006>
            <D_0040>123456789PROD</D_0040>
        </C_S006>
        <C_S007>
            <D_0044>FDX123456</D_0044>
        </C_S007>
        <C_S004>
            <D_0017>220526</D_0017>
            <D_0019>1124</D_0019>
        </C_S004>
        <C_S008>
            <D_0052>FG-08727548</D_0052>
        </C_S008>
    </S_UNG>
    <M_ORDERS_97A>
        <S_UNH>
            <D_0062>359972299</D_0062>
            <C_S009>
                <D_0065>ORDERS</D_0065>
                <D_0052>D</D_0052>
                <D_0054>97A</D_0054>
                <D_0051>UN</D_0051>
            </C_S009>
        </S_UNH>
        <S_BGM>
            <C_C002>
                <D_1001>220</D_1001>
            </C_C002>
        </S_BGM>
        <S_DTM>
            <C_C507>
                <D_2005>137</D_2005>
                <D_2380>20180526112421</D_2380>
                <D_2379>204</D_2379>
            </C_C507>
        </S_DTM>
        <S_FTX>
            <D_4451>COI</D_4451>
            <C_C108>
                <D_4440>NP</D_4440>
            </C_C108>
        </S_FTX>
        <S_FTX>
            <D_4451>ACO</D_4451>
            <C_C108>
                <D_4440>ZZ03</D_4440>
            </C_C108>
        </S_FTX>
        <S_FTX>
            <D_4451>ACP</D_4451>
            <C_C108>
                <D_4440>Z43</D_4440>
            </C_C108>
        </S_FTX>
        <G_ORDERS_97A_SG1>
            <S_RFF>
                <C_C506>
                    <D_1153>CO</D_1153>
                    <D_1154>9704875521</D_1154>
                </C_C506>
            </S_RFF>
            <S_DTM>
                <C_C507>
                    <D_2005>4</D_2005>
                    <D_2380>20220526</D_2380>
                    <D_2379>102</D_2379>
                </C_C507>
            </S_DTM>
        </G_ORDERS_97A_SG1>
        <G_ORDERS_97A_SG2>
            <S_NAD>
                <D_3035>SU</D_3035>
                <C_C082>
                    <D_3039>0001900344</D_3039>
                </C_C082>
            </S_NAD>
        </G_ORDERS_97A_SG2>
        <G_ORDERS_97A_SG12>
            <S_TOD>
                <C_C100>
                    <D_4053>DCA</D_4053>
                    <D_4052>Dedicated Carrier</D_4052>
                </C_C100>
            </S_TOD>
        </G_ORDERS_97A_SG12>
        <G_ORDERS_97A_SG28>
            <S_LIN>
                <D_1082>00010</D_1082>
            </S_LIN>
            <S_IMD>
                <D_7077>C</D_7077>
                <C_C273>
                    <D_7008>IT09738</D_7008>
                </C_C273>
            </S_IMD>
            <S_IMD>
                <D_7077>E</D_7077>
                <C_C273>
                    <D_7008>ZZZZ DLK LBL D5-9999U NVP Y-TPM</D_7008>
                    <D_7008_1> WIN</D_7008_1>
                </C_C273>
            </S_IMD>
            <S_QTY>
                <C_C186>
                    <D_6063>21</D_6063>
                    <D_6060>47</D_6060>
                    <D_6411>EA</D_6411>
                </C_C186>
            </S_QTY>
            <S_DTM>
                <C_C507>
                    <D_2005>2</D_2005>
                    <D_2380>20220527</D_2380>
                    <D_2379>102</D_2379>
                </C_C507>
            </S_DTM>
            <S_FTX>
                <D_4451>LIN</D_4451>
                <C_C108>
                    <D_4440>ID:2093834397</D_4440>
                </C_C108>
            </S_FTX>
            <G_ORDERS_97A_SG33>
                <S_RFF>
                    <C_C506>
                        <D_1153>AIS</D_1153>
                        <D_1154>A201</D_1154>
                    </C_C506>
                </S_RFF>
            </G_ORDERS_97A_SG33>
            <G_ORDERS_97A_SG37>
                <S_LOC>
                    <D_3227>ZZZ</D_3227>
                    <C_C517>
                        <D_3225>1001</D_3225>
                    </C_C517>
                </S_LOC>
            </G_ORDERS_97A_SG37>
        </G_ORDERS_97A_SG28>
        <S_UNS>
            <D_0081>S</D_0081>
        </S_UNS>
        <S_UNT>
            <D_0074>20</D_0074>
            <D_0062>359972299</D_0062>
        </S_UNT>
    </M_ORDERS_97A>
    <S_UNE>
        <D_0060>1</D_0060>
        <D_0048>FG-08727548</D_0048>
    </S_UNE>
    <S_UNZ>
        <D_0036>1</D_0036>
        <D_0020>IG-08727547</D_0020>
    </S_UNZ>
</EDIFACTINTERCHANGE>

Looks good to me

**Comment by Jimex** [comment]
Based on the below EDIFACT structure, the UNH could have more than one occurrence in the same UNG.

 |_Service String Advice              UNA  Optional
 |____Interchange Header              UNB  Mandatory
 :    |___Functional Group Header     UNG  Conditional
 :    :   |___Message Header          UNH  Mandatory
 :    :   :   |__ User Data Segments          As required
 :    :   |__ Message Trailer         UNT  Mandatory
 :    |__ Functional Group Trailer    UNE  Conditional
 |___ Interchange Trailer             UNZ  Mandatory


So I guess the output should be like the following content, but the tricky part is that UNG is not mandatory in EDIFACT specification, some messages might be wrapped with UNG and some are not.

```xml
<S_UNA>
    <D_UNA1>:</D_UNA1>
    <D_UNA2>+</D_UNA2>
    <D_UNA3>.</D_UNA3>
    <D_UNA4>?</D_UNA4>
    <D_UNA5>*</D_UNA5>
    <D_UNA6>'</D_UNA6>
</S_UNA>
<S_UNB>
    <C_S001>
        <D_0001>UNOC</D_0001>
        <D_0002>3</D_0002>
    </C_S001>
    <C_S002>
        <D_0004>123456789PROD</D_0004>
        <D_0007>16</D_0007>
    </C_S002>
    <C_S003>
        <D_0010>FDX123456</D_0010>
    </C_S003>
    <C_S004>
        <D_0017>220526</D_0017>
        <D_0019>1124</D_0019>
    </C_S004>
    <D_0020>IG-08727547</D_0020>
    <D_0031>1</D_0031>
</S_UNB>
<FUNCTIONALGROUP>
	<S_UNG>
		<D_0038>ORDERS</D_0038>
		<C_S006>
			<D_0040>123456789PROD</D_0040>
		</C_S006>
		<C_S007>
			<D_0044>FDX123456</D_0044>
		</C_S007>
		<C_S004>
			<D_0017>220526</D_0017>
			<D_0019>1124</D_0019>
		</C_S004>
		<C_S008>
			<D_0052>FG-08727548</D_0052>
		</C_S008>
	</S_UNG>
	<M_ORDERS_97A>
		<S_UNH>
			<D_0062>359972299</D_0062>
			<C_S009>
				<D_0065>ORDERS</D_0065>
				<D_0052>D</D_0052>
				<D_0054>97A</D_0054>
				<D_0051>UN</D_0051>
			</C_S009>
		</S_UNH>
		<S_BGM>
			<C_C002>
				<D_1001>220</D_1001>
			</C_C002>
		</S_BGM>
		<S_DTM>
			<C_C507>
				<D_2005>137</D_2005>
				<D_2380>20180526112421</D_2380>
				<D_2379>204</D_2379>
			</C_C507>
		</S_DTM>
		<S_FTX>
			<D_4451>COI</D_4451>
			<C_C108>
				<D_4440>NP</D_4440>
			</C_C108>
		</S_FTX>
		<S_FTX>
			<D_4451>ACO</D_4451>
			<C_C108>
				<D_4440>ZZ03</D_4440>
			</C_C108>
		</S_FTX>
		<S_FTX>
			<D_4451>ACP</D_4451>
			<C_C108>
				<D_4440>Z43</D_4440>
			</C_C108>
		</S_FTX>
		<G_ORDERS_97A_SG1>
			<S_RFF>
				<C_C506>
					<D_1153>CO</D_1153>
					<D_1154>9704875521</D_1154>
				</C_C506>
			</S_RFF>
			<S_DTM>
				<C_C507>
					<D_2005>4</D_2005>
					<D_2380>20220526</D_2380>
					<D_2379>102</D_2379>
				</C_C507>
			</S_DTM>
		</G_ORDERS_97A_SG1>
		<G_ORDERS_97A_SG2>
			<S_NAD>
				<D_3035>SU</D_3035>
				<C_C082>
					<D_3039>0001900344</D_3039>
				</C_C082>
			</S_NAD>
		</G_ORDERS_97A_SG2>
		<G_ORDERS_97A_SG12>
			<S_TOD>
				<C_C100>
					<D_4053>DCA</D_4053>
					<D_4052>Dedicated Carrier</D_4052>
				</C_C100>
			</S_TOD>
		</G_ORDERS_97A_SG12>
		<G_ORDERS_97A_SG28>
			<S_LIN>
				<D_1082>00010</D_1082>
			</S_LIN>
			<S_IMD>
				<D_7077>C</D_7077>
				<C_C273>
					<D_7008>IT09738</D_7008>
				</C_C273>
			</S_IMD>
			<S_IMD>
				<D_7077>E</D_7077>
				<C_C273>
					<D_7008>ZZZZ DLK LBL D5-9999U NVP Y-TPM</D_7008>
					<D_7008_1> WIN</D_7008_1>
				</C_C273>
			</S_IMD>
			<S_QTY>
				<C_C186>
					<D_6063>21</D_6063>
					<D_6060>47</D_6060>
					<D_6411>EA</D_6411>
				</C_C186>
			</S_QTY>
			<S_DTM>
				<C_C507>
					<D_2005>2</D_2005>
					<D_2380>20220527</D_2380>
					<D_2379>102</D_2379>
				</C_C507>
			</S_DTM>
			<S_FTX>
				<D_4451>LIN</D_4451>
				<C_C108>
					<D_4440>ID:2093834397</D_4440>
				</C_C108>
			</S_FTX>
			<G_ORDERS_97A_SG33>
				<S_RFF>
					<C_C506>
						<D_1153>AIS</D_1153>
						<D_1154>A201</D_1154>
					</C_C506>
				</S_RFF>
			</G_ORDERS_97A_SG33>
			<G_ORDERS_97A_SG37>
				<S_LOC>
					<D_3227>ZZZ</D_3227>
					<C_C517>
						<D_3225>1001</D_3225>
					</C_C517>
				</S_LOC>
			</G_ORDERS_97A_SG37>
		</G_ORDERS_97A_SG28>
		<S_UNS>
			<D_0081>S</D_0081>
		</S_UNS>
		<S_UNT>
			<D_0074>20</D_0074>
			<D_0062>359972299</D_0062>
		</S_UNT>
	</M_ORDERS_97A>
	<S_UNE>
		<D_0060>1</D_0060>
		<D_0048>FG-08727548</D_0048>
	</S_UNE>
</FUNCTIONALGROUP>
<S_UNZ>
    <D_0036>1</D_0036>
    <D_0020>IG-08727547</D_0020>
</S_UNZ>
.```
