### ISSUE TITLE
If EDI contains arbitory UNA+, parser failed to parse the file

### ISSUE THREAD

**Issue by Orca007** [sapstern/-edifactconverter-#35]
The EDI contains UNA+, but not the key string, please see line 8. The EDI file is:
`UNA:+.? '
UNB+UNOX:3+SABICSAP:14+3PL_APAC:14+220830:1923+00000217885470'
UNH+0010126665+PARTIN:D:01B:UN'
BGM+10+0000000217885470+5'
DTM+137:20220830:204'
UNS+D'
NAD+OY+0010126665++NAGASE PHILIPPINES INTL.::SERVICES CORP.+UNIT 4, 125 NORTH SCIENCE AVENUE,+BINAN, LAGUNA+13+4024+PH'
FTX+WHI++MAXPARTIALS+9'
FTX+WHI++PARTIALITEM+C'
FTX+WHI++TOLOVER+10.0'
FTX+WHI++TOLUNDER+10.0'
CTA+CN+:NAGASE PHILIPPINES INTL.'
COM+25117414:TE'
COM+26250085:FX'
COM+NA:EM'
TOD+6++:::CIF'
LOC+1+:::MANILA'
UNT+16+0010126665'
UNZ+1+00000217885470'
`

It caused by com.sapstern.openedifact.sax.EdifactSaxParserToXML line 410. please check.

Thanks!

**Comment by sapstern** [comment]
Could not reproduce the error, I get:

<?xml version="1.0" encoding="UTF-8"?>
<EDIFACTINTERCHANGE>
	<S_UNA>
		<D_UNA1>:</D_UNA1>
		<D_UNA2>+</D_UNA2>
		<D_UNA3>.</D_UNA3>
		<D_UNA4>?</D_UNA4>
		<D_UNA5>*</D_UNA5>
		<D_UNA6>'</D_UNA6>
	</S_UNA>
	<S_UNB>
		<C_S001>
			<D_0001>UNOX</D_0001>
			<D_0002>3</D_0002>
		</C_S001>
		<C_S002>
			<D_0004>SABICSAP</D_0004>
			<D_0007>14</D_0007>
		</C_S002>
		<C_S003>
			<D_0010>3PL_APAC</D_0010>
			<D_0007>14</D_0007>
		</C_S003>
		<C_S004>
			<D_0017>220830</D_0017>
			<D_0019>1923</D_0019>
		</C_S004>
		<D_0020>00000217885470</D_0020>
	</S_UNB>
	<M_PARTIN_01B>
		<S_UNH>
			<D_0062>0010126665</D_0062>
			<C_S009>
				<D_0065>PARTIN</D_0065>
				<D_0052>D</D_0052>
				<D_0054>01B</D_0054>
				<D_0051>UN</D_0051>
			</C_S009>
		</S_UNH>
		<S_BGM>
			<C_C002>
				<D_1001>10</D_1001>
			</C_C002>
			<C_C106>
				<D_1004>0000000217885470</D_1004>
			</C_C106>
			<D_1225>5</D_1225>
		</S_BGM>
		<S_DTM>
			<C_C507>
				<D_2005>137</D_2005>
				<D_2380>20220830</D_2380>
				<D_2379>204</D_2379>
			</C_C507>
		</S_DTM>
		<S_UNS>
			<D_0081>D</D_0081>
		</S_UNS>
		<G_PARTIN_01B_SG4>
			<S_NAD>
				<D_3035>OY</D_3035>
				<C_C082>
					<D_3039>0010126665</D_3039>
				</C_C082>
				<C_C080>
					<D_3036>NAGASE PHILIPPINES INTL.</D_3036>
					<D_3036_2>SERVICES CORP.</D_3036_2>
				</C_C080>
				<C_C059>
					<D_3042>UNIT 4, 125 NORTH SCIENCE AVENUE,</D_3042>
				</C_C059>
				<D_3164>BINAN, LAGUNA</D_3164>
				<C_C819>
					<D_3229>13</D_3229>
				</C_C819>
				<D_3251>4024</D_3251>
				<D_3207>PH</D_3207>
			</S_NAD>
			<S_FTX>
				<D_4451>WHI</D_4451>
				<C_C107>
					<D_4441>MAXPARTIALS</D_4441>
				</C_C107>
				<C_C108>
					<D_4440>9</D_4440>
				</C_C108>
			</S_FTX>
			<S_FTX>
				<D_4451>WHI</D_4451>
				<C_C107>
					<D_4441>PARTIALITEM</D_4441>
				</C_C107>
				<C_C108>
					<D_4440>C</D_4440>
				</C_C108>
			</S_FTX>
			<S_FTX>
				<D_4451>WHI</D_4451>
				<C_C107>
					<D_4441>TOLOVER</D_4441>
				</C_C107>
				<C_C108>
					<D_4440>10.0</D_4440>
				</C_C108>
			</S_FTX>
			<S_FTX>
				<D_4451>WHI</D_4451>
				<C_C107>
					<D_4441>TOLUNDER</D_4441>
				</C_C107>
				<C_C108>
					<D_4440>10.0</D_4440>
				</C_C108>
			</S_FTX>
			<G_PARTIN_01B_SG7>
				<S_CTA>
					<D_3139>CN</D_3139>
					<C_C056>
						<D_3412>NAGASE PHILIPPINES INTL.</D_3412>
					</C_C056>
				</S_CTA>
				<S_COM>
					<C_C076>
						<D_3148>25117414</D_3148>
						<D_3155>TE</D_3155>
					</C_C076>
				</S_COM>
				<S_COM>
					<C_C076>
						<D_3148>26250085</D_3148>
						<D_3155>FX</D_3155>
					</C_C076>
				</S_COM>
				<S_COM>
					<C_C076>
						<D_3148>NA</D_3148>
						<D_3155>EM</D_3155>
					</C_C076>
				</S_COM>
			</G_PARTIN_01B_SG7>
			<G_PARTIN_01B_SG9>
				<S_TOD>
					<D_4055>6</D_4055>
					<C_C100>
						<D_4052>CIF</D_4052>
					</C_C100>
				</S_TOD>
				<S_LOC>
					<D_3227>1</D_3227>
					<C_C517>
						<D_3224>MANILA</D_3224>
					</C_C517>
				</S_LOC>
			</G_PARTIN_01B_SG9>
		</G_PARTIN_01B_SG4>
		<S_UNT>
			<D_0074>16</D_0074>
			<D_0062>0010126665</D_0062>
		</S_UNT>
	</M_PARTIN_01B>
	<S_UNZ>
		<D_0036>1</D_0036>
		<D_0020>00000217885470</D_0020>
	</S_UNZ>
</EDIFACTINTERCHANGE>

**Comment by sapstern** [comment]
Could not reproduce. 
![Screenshot_2022-09-10_17-44-52](https://user-images.githubusercontent.com/10392736/189491019-0540b12c-7734-4ba7-9fbf-0cd0d3bb2d3b.png)
