### ISSUE TITLE
No need to add a fieldDelimiter for the UNA segment when converting to flat file

### ISSUE THREAD

**Issue by Abifen** [sapstern/-edifactconverter-#36]
In the conversion of a XML to Flat file the UNA is generated with a fieldDelimiter but this is not required for this segment.

For example with this UNA data in the XML:
```
<S_UNA>
<D_UNA1>:</D_UNA1>
<D_UNA2>+</D_UNA2>
<D_UNA3>.</D_UNA3>
<D_UNA4>?</D_UNA4>
<D_UNA5> </D_UNA5>
<D_UNA6>'</D_UNA6>
</S_UNA>
```

The generated flat file start with:
UNA+:+.? '
instead of :
UNA:+.? '

To solve this, we could modify code near line 411 in EdifactSaxParserToFlat.java :
```
            //Beginn des EDI segmentstrings
            if (eName.equals("S_UNA")) {//Abifen*** no fieldDelimiter for UNA segment
                emit(eName.substring(2));
            }
            else {
                emit(eName.substring(2)+fieldDelimiter);
            }
            return;
```

**Comment by sapstern** [comment]
I incorporated this bugfix, thanks
